# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-09 11:00
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buildings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('building', models.CharField(max_length=254)),
                ('building_l', models.CharField(max_length=254)),
                ('addr_stree', models.CharField(max_length=254)),
                ('phone', models.CharField(max_length=254)),
                ('water', models.CharField(max_length=254)),
                ('source', models.CharField(max_length=254)),
                ('area', models.CharField(max_length=254)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
    ]
