# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-22 13:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_houses'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='houses',
            options={},
        ),
    ]
