# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-22 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_auto_20160722_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='houses',
            name='name',
            field=models.CharField(default='House Name', max_length=50),
        ),
    ]
