# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-22 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_procareas'),
    ]

    operations = [
        migrations.AddField(
            model_name='procareas',
            name='name',
            field=models.CharField(default='protected', max_length=50),
        ),
    ]
